import type { Metadata } from "next";
import "./globals.css";
import "./reset.css";
import styles from "./layout.module.css";
import { ClerkProvider, RedirectToSignIn, Show } from "@clerk/nextjs";
import { SidePanel } from "@/containers/SidePanel/SidePanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <Show when="signed-out">
            <RedirectToSignIn />
          </Show>
          <Show when="signed-in">
            <div className={styles["app-layout"]}>
              <SidePanel />
              {children}
            </div>
          </Show>
        </ClerkProvider>
      </body>
    </html>
  );
}
